apiVersion: v1
kind: Service
metadata:
  name: openai-mxb-cc-service
  namespace: default
spec:
  clusterIP: None
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: openai-mxb-cc
  type: ClusterIP
