apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openai-mxb-cc
  name: openai-mxb-cc
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openai-mxb-cc
  template:
    metadata:
      labels:
        app: openai-mxb-cc
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-mxb-cc-secret
                  key: OPENAI_API_KEY
          image: ghcr.io/mxbcc/openai.mxb.cc:v1.0.0
          imagePullPolicy: IfNotPresent
          name: openai-mxb-cc
          resources: { }
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: { }
